name: window_manager_extra
description: This plugin allows Flutter desktop apps to resizing and repositioning the window.
version: 0.5.1
homepage: https://github.com/huawt/window_manager_extra

platforms:
  linux:
  macos:
  windows:

topics:
  - window
  - window-resize
  - window-manager
  - desktop
  - desktop-window

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.2

dev_dependencies:
  dependency_validator: ^3.0.0
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.2

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: WindowManagerExtraPlugin
      macos:
        pluginClass: WindowManagerExtraPlugin
      windows:
        pluginClass: WindowManagerExtraPlugin
